level: "prod"

project:
  mainIngress: pinstagram-static-main-ingress
  testProject: pinstargram-test-project

app:
  pinstagramNetworkApp: pinstagram-network-app
  pinstagramApp: pinstagram-app
  authApp: auth-app
  geoApp: geo-app
  contentsApp: contents-app
  talkApp: talk-app
  eventApp: event-app
  defaultApp: default-app


service:
  defaultBackend: defaultbackend
  staticService: pinstagram-static-service
  authService: auth-service
  contentsService: contents-service
  geoService: geo-service
  talkService: talk-service
  eventService: event-service

deploy:
  auth: auth-deploy
  contents: contents-deploy
  geo: geo-deploy
  talk: talk-deploy
  event: event-deploy
path:
  authPath: /auth/*
  contentsPath: /contents/*
  geoPath: /geometry/*
  talkPath: /talk/*
  eventPath : /event/*
  healthCheck:
    authPath: /auth/healthCheck
    contentsPath: /contents/healthCheck
    geoPath: /geometry/healthCheck
    talkPath: /talk/healthCheck
    eventPath: /event/healthCheck
port:
  frontPort: 80
  defaultPort: 8080
  authPort: 8081
  contentsPort: 8082
  geoPort: 8083
  talkPort: 8084
  eventPort: 8085

tier:
  server: server

ssl:
  domain: www.coguri.shop
  appName: cert-app

images:
  auth: gcr.io/eminent-nation-320908/pinstagram-auth:0.1.1
  contents: gcr.io/eminent-nation-320908/pinstagram-contents:0.1.0
  geo: gcr.io/eminent-nation-320908/pinstagram-geo:0.1.0
  talk: gcr.io/eminent-nation-320908/pinstagram-talk:0.1.1
  event: gcr.io/eminent-nation-320908/pinstagram-event:0.1.0
