apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deploy.event}}
  labels:
    app: {{.Values.app.eventApp}}
spec:
  selector:
    matchLabels:
      app: {{.Values.app.eventApp}}
      tier: {{.Values.tier.server}}
  template:
    metadata:
      labels:
        app: {{.Values.app.eventApp}}
        tier: {{.Values.tier.server}}
    spec:
      containers:
        - name: {{.Values.app.eventApp}}
          image: {{.Values.images.event}}
          ports:
            - containerPort: {{.Values.port.eventPort}}
              hostPort:  {{.Values.port.eventPort}}
          readinessProbe:
            periodSeconds: 60
            httpGet:
              port: {{.Values.port.eventPort}}
              path: {{.Values.path.healthCheck.eventPath}}
              scheme: HTTP

